addons:
  apt:
    packages:
      - libjpeg62

language: python
python: 3.6

cache:
  directories:
    - $HOME/build_dials
  timeout: 1000

jobs:
  include:
    - stage: build
      name: "Syntax validation"
      addons: false
      cache: false
      before_cache: false
      python: 3.7
      script:
         - python3 -m compileall -q *

    - name: "Build"
      install:
         # Setup a base installation
         - ./.travis/setup-base

         # Inject DXTBX
         - rm -rf $HOME/build_dials/modules/dxtbx
         - mv $HOME/build/cctbx/dxtbx $HOME/build_dials/modules/dxtbx

         # Update CCTBX
         - $HOME/build_dials/modules/dxtbx/.travis/clean-cctbx
         - $HOME/build_dials/modules/dxtbx/.travis/update-cctbx

      before_script:
         # Enter CCTBX environment
         - cd $HOME/build_dials/build
         - cat setpaths.sh
         - . setpaths.sh

         # Prepare for the build step
         - libtbx.configure .

      script:
         # Parallel builds do not work. Only spend at most 40 minutes on a build.
         # This allows incremental building, so if the build can't be finished within the allotted time
         # it will be resumed from that point in the next build.
         - $HOME/build_dials/modules/dxtbx/.travis/build-for 40m

    - stage: test
      before_script:
         # Inject DXTBX. Again.
         - rm -rf $HOME/build_dials/modules/dxtbx
         - mv $HOME/build/cctbx/dxtbx $HOME/build_dials/modules/dxtbx

         # Enter CCTBX environment
         - cd $HOME/build_dials/build
         - . setpaths.sh

         # If needed allow up to further 30 minutes worth of building time
         - $HOME/build_dials/modules/dxtbx/.travis/build-for 30m if_required

      script:
         # Finally. Do what we are here for. Run tests. Yay.
         - cd $HOME/build_dials/modules/dxtbx
         - pytest -ra -n 2
         - .travis/check-working-directory-is-clean

    - name: "Test"
      before_script:
         # Inject DXTBX. Again.
         - rm -rf $HOME/build_dials/modules/dxtbx
         - mv $HOME/build/cctbx/dxtbx $HOME/build_dials/modules/dxtbx

         # Enter CCTBX environment
         - cd $HOME/build_dials/build
         - . setpaths.sh

         # If needed allow up to further 30 minutes worth of building time
         - $HOME/build_dials/modules/dxtbx/.travis/build-for 30m if_required

      script:
         # Finally. Do what we are here for. Run tests. Yay.
         - cd $HOME/build_dials/modules/dxtbx
         - pytest -ra -n 2
         - .travis/check-working-directory-is-clean

    - name: "Flake8"
      addons: false
      cache: false
      before_cache: false
      python: 3.7
      script:
         - .travis/run-flake8
      if: type = pull_request

before_cache:
  - $HOME/build_dials/modules/dxtbx/.travis/clean-cctbx
  - cd $HOME
  - rm -rf $HOME/build_dials/modules/dxtbx
